objects/FinDock_Flow_Configuration__mdt.object
<CustomObject>
    <label>FinDock Flow Configuration</label>
    <pluralLabel>FinDock Flow Configurations</pluralLabel>
    <fields>
        <fullName>Flow_API_Name__c</fullName>
        <label>Flow API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

sfdx-source/main/default/classes/FlowLauncherController.cls
public with sharing class FlowLauncherController {
    @AuraEnabled
    public static Map<String, String> getFlowConfigurations() {
        Map<String, String> returnList = new Map<String, String>();

        for ( FinDock_Flow_Configuration__mdt flowConfig : [select id, DeveloperName, Flow_Api_Name__c  from FinDock_Flow_Configuration__mdt ] ) {
            returnList.put( flowConfig.DeveloperName , flowConfig.Flow_Api_Name__c);
        }
        return returnList;
    }
}